### ISSUE TITLE
99/100% CPU usage

### ISSUE THREAD

**Issue by ketheriel** [SpunkyBot/spunkybot#30] opened 2015-07-10 17:34 UTC
Hi,

I was helping a friend installing and testing spunkybot 1.4.0 and we found out that it's currently using 100% CPU. I've found an old bug report claiming it happens when rules.conf was empty but our file isn't empty.

Is there anything I can help with to improve this? I would suppose it's not normal to chunk a whole CPU.

**Comment by urthub** [comment] 2015-07-11 19:53
Hi,

yes in previous versions it was possible that a misconfiguration could lead to high CPU load, but this should not be possible anymore.
I would need more info to reproduce your issue, could you please forward the file "devel.log" located in spunkybot root-folder?
Additionally it would be good to get the "conf/settings.conf" file, too (do not forget to hide your rcon password).
Please send all info to feedback(at)spunkybot.de

**Comment by ketheriel** [comment] 2015-07-17 21:10
I will provide this info in the days. Right now I don't have access.

**Comment by alexanderkress** [comment] 2015-08-01 16:09
Hi,
any update on your site?
I was not able to reproduce a similar behaviour with the latest version, which will be released today.
I was testing several combinations (empty rules file, only whitespaces, line with one whitespace, file not exisiting, file not accessible for user) and was not able to see any high CPU usage.

**Comment by alexanderkress** [comment] 2015-10-24 16:36
Issue cannot be reproduced in V1.5.0 and upcoming V1.6.0.

**Closed by alexanderkress** 2015-10-24 16:36 UTC
Labels: question, support request
